// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuzvtqgbyliasiscitvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1enZ0cWdieWxpYXNpc2NpdHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2NjAzMzgsImV4cCI6MjA1NzIzNjMzOH0.hTgrhLFk9UTKXFVIQhPoZb-2xyrfW-EFCaFhPUKpLaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);